INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "gaa", "가어", "Ga", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "gay", "가요어", "Gayo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("lg", "lug", "간다어", "Ganda", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("gl", "glg", "갈리시아어; 갈레고어", "galicien", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "gem", "게르만어파 (기타)", "Germanic languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "gez", "게에즈어", "Geez", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("gd", "gla", "게일어; 스코틀랜드 게일어", "Gaelic; Scottish Gaelic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "got", "고트어", "Gothic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "gon", "곤드어", "Gondi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("gn", "grn", "과라니어", "Guarani", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("gu", "guj", "구자라트어", "Gujarati", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "grb", "그레보어", "Grebo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "grc", "그리스어 (고대) (1453년 이전)", "Ancient Greek", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("el", "gre", "그리스어 (현대) (1453년 이후)", "Modern Greek", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("el", "ell", "그리스어 (현대) (1453년 이후)", "Modern Greek", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("kl", "kal", "그린란드어; 칼랄리수트", "Greenlandic; Kalaallisut", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "gba", "그바야어", "Gbaya", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "gwi", "그위친어", "Gwich'in", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mis", "기타 언어", "Miscellaneous languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("nv", "nav", "나바호어", "Navajo; Navaho", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nah", "나와어; 나와틀어", "Nahuatl", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("na", "nau", "나우루어", "Nauru", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ssa", "나일사하라어족 (기타)", "Nilo-Saharan languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nap", "나폴리어", "Neopolitan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sai", "남아메리카 인디언 제어 (기타)", "South American Indian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("nl", "dut", "네덜란드어; 플라망어", "Dutch; Flemish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("nl", "nld", "네덜란드어; 플라망어", "Dutch; Flemish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "dum", "네덜란드어 (중세) (1050년-1350년경)", "Middle Dutch", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "new", "네와르어; 네팔바사", "Newari; Nepal", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nwc", "네와르어 (고전)", "Classical Newari; Old Newari", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ne", "nep", "네팔어", "Nepali", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nog", "노가이어", "Nogai", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "non", "노르드어 (고대)", "Old Norse", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("no", "nor", "노르웨이어", "Norwegian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("nn", "nno", "노르웨이어 (뉘노르스크); 신노르웨이어", "Norwegian Nynorsk", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("nb", "nob", "노르웨이어 (보크몰); 덴마크-노르웨이어", "Norwegian Bokmål", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nub", "누비아어군", "Nubian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ny", "nya", "니안자어; 체와어; 치체와", "Chichewa; Chewa; Nyanja", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nym", "니암웨지어", "Nyamwezi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nyo", "니오로어", "Nyoro", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "niu", "니우에어", "Niuean", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nic", "니제르코르도판어족 (기타)", "Niger-Kordofanian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "dar", "다르과어", "Dargwa", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "day", "다야크어", "Dayak", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mul", "다중 언어", "Multiple languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "dak", "다코타어", "Dakota", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("da", "dan", "덴마크어", "Danish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "del", "델라웨어어", "Delaware", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "doi", "도그라어", "Dogri", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "dgr", "도그리브어", "Dogrib", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("de", "ger", "독일어", "German", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("de", "deu", "독일어", "German", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "goh", "독일어 (고대 고지) (750년-1050년경)", "Old High German", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "gmh", "독일어 (중세 고지) (1050년-1500년경)", "Middle High German", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "dua", "두알라어", "Duala", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "dyu", "듈라어", "Dyula", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "dra", "드라비다어족 (기타)", "Dravidian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("dv", "div", "디베히어", "Divehi language", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "din", "딩카어", "Dinka language", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "lad", "라디노어; 유대스페인어", "Ladino", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "rar", "라로통가어", "Rarotongan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("lo", "lao", "라오어", "Lao", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "raj", "라자스탄어", "Rajasthani", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("lv", "lav", "라트비아어", "Latvian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("la", "lat", "라틴어", "Latin", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "rap", "라파누이어", "Rapanui", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "lah", "란다어", "Lahnda", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "lam", "람바어", "Lamba", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ru", "rus", "러시아어", "Russian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "lez", "레즈긴어", "Lezghian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("rm", "roh", "로만슈어; 레토로망어; 라이티아 로망스어", "Rhaeto-Romance", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "roa", "로망스어군 (기타)", "Romance languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "jbo", "로지반", "Lojban", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "loz", "로지어", "Lozi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "rom", "롬어; 로마니어; 집시어", "Romany", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ro", "rum", "루마니아어", "Romanian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ro", "ron", "루마니아어", "Romanian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "lua", "루바룰루아어", "Luba-Lulua", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("lu", "lub", "루바카탕가어", "Luba-Katanga", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "lus", "루샤이어", "Lushai", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "rue", "루신어", "Rusyn", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "luo", "루오어 (케냐와 탄자니아)", "Luo (Kenya and Tanzania)", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "lui", "루이세뇨어", "Luiseno", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("lb", "ltz", "룩셈부르크어", "Luxembourgish; Letzeburgesch", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "lun", "룬다어", "Lunda", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("rn", "run", "룬디어", "Rundi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "smj", "룰레 사미어", "Lule Sami", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("rw", "kin", "르완다어; 키냐르완다어", "Kinyarwanda", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("lt", "lit", "리투아니아어", "Lithuanian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("li", "lim", "림뷔르흐어", "Limburgan; Limburger; Limburgish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ln", "lin", "링갈라어", "Lingala", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mag", "마가드어; 마가히어", "Magahi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mno", "마노보어군", "Manobo languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mni", "마니푸르어; 마니푸리어", "Manipuri", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("mg", "mlg", "마다가스카르어", "Malagasy", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mad", "마두라어", "Madurese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("mr", "mar", "마라티어", "Marathi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mwr", "마르와르어", "Marwari", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "chm", "마리어", "Mari", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mas", "마사이어", "Masai", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("mh", "mah", "마셜어", "Marshallese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "myn", "마야어족", "Mayan languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("mi", "mao", "마오리어", "Maori", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("mi", "mri", "마오리어", "Maori", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mai", "마이틸라어; 마이틸리어", "Maithili", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mak", "마카사르어", "Makasar", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("mk", "mac", "마케도니아어", "Macedonian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("mk", "mkd", "마케도니아어", "Macedonian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mdr", "만다르어", "Mandar", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "man", "만데어; 만딩고어", "Mandingo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mnc", "만주어", "Manchu", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ml", "mal", "말라얄람어", "Malayalam", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ms", "may", "말레이어", "Malay", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ms", "msa", "말레이어", "Malay", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("gv", "glv", "맨어; 맹크스어", "Manx", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "men", "멘데어", "Mende", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mos", "모시어", "Mossi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mdf", "모크샤어", "Moksha", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "moh", "모호크어", "Mohawk", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mkh", "몬크메르어파 (기타)", "Mon-Khmer languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("mo", "mol", "몰도바어", "Moldavian; Moldovan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("mt", "mlt", "몰타어", "Maltese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "lol", "몽고어", "Mongo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("mn", "mon", "몽골어", "Mongolian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "hmn", "몽어", "Hmong", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mus", "무스코지어; 크리크어", "Creek", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mun", "문다어파", "Munda languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "min", "미낭카바우어", "Minangkabau", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mwl", "미란데어", "Mirandese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mic", "미크맥어", "Mi'kmaq; Micmac", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "und", "미확인 언어", "Undetermined", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bai", "바밀레케어계", "Bamileke languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bas", "바사어", "Basa", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ba", "bak", "바슈키르어", "Bashkir", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("eu", "baq", "바스크어", "Basque", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("eu", "eus", "바스크어", "Basque", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "vai", "바이어", "Vai", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bar", "바바리아어", "Bavarian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bad", "반다어", "Banda", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bnt", "반투어군 (기타)", "Bantu languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bal", "발루치어", "Baluchi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ban", "발리어", "Balinese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bat", "발트어파 (기타)", "Baltic languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("bm", "bam", "밤바라어", "Bambara", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("my", "bur", "버마어", "Burmese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("my", "mya", "버마어", "Burmese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ber", "베르베르어파 (기타)", "Berber languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bej", "베자어", "Beja", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("vi", "vie", "베트남어", "Vietnamese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ve", "ven", "벤다어", "Venda", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("be", "bel", "벨라루스어", "Belarusian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bem", "벰바어", "Bemba", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("bn", "ben", "벵골어", "Bengali", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("bs", "bos", "보스니아어", "Bosnian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bho", "보지푸르어; 보지푸리어", "Bhojpuri", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "vot", "보트어", "Votic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("vo", "vol", "볼라퓌크", "Volapük", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bug", "부기어", "Buginese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bua", "부리아트어", "Buriat", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nai", "북아메리카 인디언 제어", "North American Indian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("bg", "bul", "불가리아어", "Bulgarian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bra", "브라지어", "Braj", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("br", "bre", "브르타뉴어", "Breton", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bla", "블랙풋어; 식시카어", "Siksika", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "byn", "블린어", "Blin; Bilin", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bin", "비니어", "Bini", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("bi", "bis", "비슐라마어", "Bislama", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "bik", "비콜어", "Bikol", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("bh", "bih", "비하르어", "Bihari", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sc", "srd", "사르데냐어", "Sardinian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sam", "사마리아 아람어", "Samaritan Aramaic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sm", "smo", "사모아어", "Samoan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sma", "사미어 (남)", "Southern Sami", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "smj", "사미어 (룰레)", "Lule Sami", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("se", "sme", "사미어 (북)", "Northern Sami", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sms", "사미어 (스콜트)", "Skolt Sami", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "smn", "사미어 (이나리)", "Inari Sami", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "smi", "사미어계 (기타)", "langues sami", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sas", "사사크어", "Sasak", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "zap", "사포텍어", "Zapotec", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sad", "산다웨어", "Sandawe", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sa", "san", "산스크리트어", "Sanskrit", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sat", "산탈어", "Santali", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sg", "sag", "상고어", "Sango", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sal", "살리시어족", "Salishan languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "chy", "샤이엔어", "Cheyenne", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "shn", "샨어", "Shan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "srr", "세레르어", "Serer", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sr", "scc", "세르비아어", "Serbian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sr", "srp", "세르비아어", "Serbian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ceb", "세부어; 세부아노어", "Cebuano", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sel", "셀쿠프어", "Selkup", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sem", "셈어파 (기타)", "Semitic languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sog", "소그드어", "Sogdian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "hsb", "소르비아어 (고지)", "Upper Sorbian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "dsb", "소르비아어 (저지)", "Lower Sorbian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "wen", "소르비아어계", "Sorbian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("so", "som", "소말리어", "Somali", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("st", "sot", "소토어 (남)", "Southern Sotho", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nso", "소토어 (북)", "Pedi; Sepedi; Northern Sotho", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "son", "송가이어", "Songhai", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sn", "sna", "쇼나어", "Shona", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sux", "수메르어", "Sumerian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sus", "수수어", "Susu", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sio", "수어족", "Siouan languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "suk", "수쿠마어", "Sukuma", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sgn", "수화, 각종", "Sign languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("su", "sun", "순다어", "Sundanese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ss", "ssw", "스와티어", "Swati", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sw", "swa", "스와힐리어; 키스와힐리어", "Swahili", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sv", "swe", "스웨덴어", "Swedish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sco", "스코트어", "Scots", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("es", "spa", "스페인어; 에스파냐어; 카스티야어", "Spanish; Castilian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("cu", "chu", "슬라브어 (고대 교회); 고대 슬라브어; 교회 슬라브어; 고대 불가리아어", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sla", "슬라브어파 (기타)", "Slavic languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "den", "슬레이비어 (아타파스카)", "Slave (Athapascan)", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sk", "slo", "슬로바키아어", "Slovak", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sk", "slk", "슬로바키아어", "Slovak", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sl", "slv", "슬로베니아어", "Slovenian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sit", "시노티베트어족 (기타)", "Sino-Tibetan languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sid", "시다모어", "Sidamo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "syr", "시리아어", "Syriac", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "scn", "시칠리아어", "Sicilian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sd", "snd", "신드어", "Sindhi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("si", "sin", "싱할라어", "Sinhala; Sinhalese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ii", "iii", "쓰촨 이어", "Sichuan Yi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ada", "아당메어", "Adangme", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ady", "아디게어", "Adyghe; Adygei", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("an", "arg", "아라곤어", "Aragonese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "arw", "아라와크어", "Arawak", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "arn", "아라우칸어", "Araucanian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "arp", "아라파호어", "Arapaho", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "arc", "아람어", "Aramaic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ar", "ara", "아랍어", "Arabic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("hy", "arm", "아르메니아어", "Armenian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("hy", "hye", "아르메니아어", "Armenian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("av", "ava", "아바르어", "Avar", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ae", "ave", "아베스타어", "Avestan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "aah", "아라페시어, 아부", "Arapesh, Abu'", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("as", "asm", "아삼어", "Assamese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ast", "아스투리아스어; 바블리어", "Asturian; Bable", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "awa", "아와드어", "Awadhi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ain", "아이누어", "Ainu", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ay", "aym", "아이마라어", "Aymara", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("is", "ice", "아이슬란드어", "Icelandic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("is", "isl", "아이슬란드어", "Icelandic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ht", "hat", "아이티 크리올어", "Haitian; Haitian Creole", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ga", "gle", "아일랜드어", "Irish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sga", "아일랜드어 (고대) (900년 이전)", "Old Irish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "mga", "아일랜드어 (중세) (900년-1200년경)", "Middle Irish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("az", "aze", "아제르바이잔어; 아제리어", "Azeri; Azerbaijani", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ace", "아체어", "Achinese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ach", "아촐리어", "Acoli", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "akk", "아카드어", "Akkadian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ak", "aka", "아칸어", "Akan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ath", "아타파스카어군", "Athapascan languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("aa", "aar", "아파르어", "Afar", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "apa", "아파치 제어", "Apache languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "afa", "아프리카아시아어족; 함셈어족 (기타)", "Afro-Asiatic languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("af", "afr", "아프리칸스어", "Afrikaans", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "afh", "아프리힐리어", "Afrihili", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "alg", "알공킨어파", "Algonquian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ale", "알류트어", "Aleut", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sq", "alb", "알바니아어", "Albanian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("sq", "sqi", "알바니아어", "Albanian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "alt", "남부 알타이어", "Southern Altai", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tut", "알타이어족 (기타)", "Altaic languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("am", "amh", "암하라어", "Amharic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ab", "abk", "압하스어; 압수아어", "Abkhazian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "yao", "야오어", "Yao", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "sah", "야쿠트어", "Yakut", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "yap", "야프어", "Yapese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "myv", "에르지아어", "Erzya", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("et", "est", "에스토니아어", "Estonian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("eo", "epo", "에스페란토", "Esperanto", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ewo", "에원도어; 야운데어", "Ewondo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ee", "ewe", "에웨어", "Ewe", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "eka", "에카주크어", "Ekajuk language", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "efi", "에피크어", "Efik", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "elx", "엘람어", "Elamite", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("en", "eng", "영어", "English", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ang", "영어 (고대); 앵글로색슨어 (450년-1100년경)", "Old English", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "enm", "영어 (중세) (1100년-1500년경)", "Middle English", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("om", "orm", "오로모어; 갈라어", "Oromo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("or", "ori", "오리야어", "Oriya", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "osa", "오세이지어", "Osage", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("os", "oss", "오세트어", "Ossetian; Ossetic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "aus", "오스트레일리아어족", "Australian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "map", "오스트로네시아어족 (기타)", "Austronesian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("oj", "oji", "오지브와어", "Ojibwa", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("oc", "oci", "오크어; 옥시탕; 랑그도크어; 프로방스어 (1500년 이후)", "Occitan; Provençal", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "oto", "오토미어군", "Otomian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "war", "와라이어", "Waray", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "was", "와쇼어", "Washo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "wak", "와카시어족", "Wakashan languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "wal", "왈라모어; 월라이타어", "Walamo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("wa", "wln", "왈론어", "Walloon", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("yo", "yor", "요루바어", "Yoruba", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "uga", "우가리트어", "Ugaritic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "udm", "우드무르트어", "Udmurt", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ur", "urd", "우르두어", "Urdu", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("uz", "uzb", "우즈베크어", "Uzbek", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("uk", "ukr", "우크라이나어", "Ukrainian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "umb", "움분두어", "Umbundu", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("wo", "wol", "월로프어", "Wolof", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("cy", "wel", "웨일스어", "Welsh", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("cy", "cym", "웨일스어", "Welsh", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ug", "uig", "위구르어", "Uighur", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "jrb", "유대아랍어", "Judeo-Arabic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "jpr", "유대페르시아어", "Judeo-Persian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ypk", "유피크어군", "Yupik languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("nr", "nbl", "은데벨레어 (남)", "South Ndebele", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("nd", "nde", "은데벨레어 (북)", "North Ndebele", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ng", "ndo", "은동가어", "Ndonga", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nzi", "은제마어", "Nzima", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nyn", "은콜레어; 니안콜레어", "Nyankole", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ig", "ibo", "이그보어", "Igbo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("iu", "iku", "이누크티투트어", "Inuktitut", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ik", "ipk", "이누피아크어; 북부 이누이트어", "Inupiaq", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("io", "ido", "이도", "Ido", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("yi", "yid", "이디시어", "Yiddish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ira", "이란어군 (기타)", "Iranian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "iro", "이로쿼이어족", "Iroquoian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "iba", "이반어", "Iban", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ijo", "이조어", "Ijo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "egy", "이집트어 (고대)", "Ancient Egyptian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("it", "ita", "이탈리아어", "Italian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "art", "인공 언어 (기타)", "Artificial languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "inh", "인구시어", "Ingush", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("id", "ind", "인도네시아어", "Indonesian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "inc", "인도아리아어군 (기타)", "Indic languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ine", "인도유럽어족 (기타)", "Indo-European languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ia", "ina", "인테르링구아 (국제보조어협회)", "Interlingua (International Auxiliary Language Association)", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ie", "ine", "인테르링구에; 옥시덴탈", "Interlingue", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ilo", "일로코어; 일로카노어", "Iloko", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ja", "jpn", "일본어", "Japanese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("jv", "jav", "자바어", "Javanese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "znd", "잔데어; 아잔데어", "Zande", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "nds", "저지 색슨어; 저지 독일어", "Low German; Low Saxon", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "zen", "제나가어", "Zenaga", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ka", "geo", "조지아어", "Georgian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ka", "kat", "조지아어", "Georgian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("dz", "dzo", "종카어", "Dzongkha", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("za", "zha", "좡어", "Zhuang; Chuang", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "zun", "주니어", "Zuni", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("zu", "zul", "줄루어", "Zulu", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("zh", "chi", "중국어", "Chinese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("zh", "zho", "중국어", "Chinese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "cai", "중앙아메리카 인디언 제어 (기타)", "Central American Indian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "chg", "차가타이어", "Chagatai", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ch", "cha", "차모로어", "Chamorro", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "cmc", "참어군", "Chamic languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "chr", "체로키어", "Cherokee", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ce", "che", "체첸어", "Chechen", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("cs", "cze", "체코어", "Czech", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("cs", "ces", "체코어", "Czech", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "cho", "촉토어", "Choctaw", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ts", "tso", "총가어", "Tsonga", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("cv", "chv", "추바슈어", "Chuvash", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "chk", "추크어; 트루크어", "Chuukese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("tn", "tsn", "츠와나어", "Tswana", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "chn", "치누크 통상어", "Chinook jargon", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "chb", "치브차어", "Chibcha", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "chp", "치페위안어", "Chipewyan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tsi", "침시아어", "Tsimshian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("kr", "kau", "카누리어", "Kanuri", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "cad", "카도어", "Caddo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "krc", "카라차이발카르어", "Karachay-Balkar", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kaa", "카라칼파크어", "Kara-Kalpak", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kar", "카렌어", "Karen", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "car", "카리브어", "Carib", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kbd", "카바르디아어", "Kabardian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kab", "카빌어", "Kabyle", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ks", "kas", "카슈미르어", "Kashmiri", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "csb", "카슈브어", "Kashubian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kha", "카시어", "Khasi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kaw", "카위어", "Kawi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("kk", "kaz", "카자흐어", "Kazakh", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kac", "카친어", "Kachin", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ca", "cat", "카탈루냐어; 카탈란", "Catalan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "cau", "카프카스 제어 (기타)", "Caucasian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("kn", "kan", "칸나다어", "Kannada", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "xal", "칼미크어", "Kalmyk; Oirat", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kam", "캄바어", "Kamba", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("qu", "que", "케추아어", "Quechua", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "cel", "켈트어파 (기타)", "Celtic languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("co", "cos", "코르시카어", "Corsican", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("kv", "kom", "코미어", "Komi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("xh", "xho", "코사어", "Xhosa", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kus", "코스라에어; 쿠사이에어", "Kosraean", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "khi", "코이산어족 (기타)", "Khoisan languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("kw", "cor", "콘월어", "Cornish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kok", "콘칸어", "Konkani", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "cop", "콥트어", "Coptic", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("kg", "kon", "콩고어", "Kongo", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("kj", "kua", "콰냐마어", "Kuanyama; Kwanyama", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kru", "쿠루크어", "Kurukh", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ku", "kur", "쿠르드어", "Kurdish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kum", "쿠미크어", "Kumyk", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "cus", "쿠시어파 (기타)", "Cushitic languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kut", "쿠테나이어", "Kutenai", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("hr", "scr", "크로아티아어", "Croatian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("hr", "hrv", "크로아티아어", "Croatian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kro", "크루어", "Kru", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "cpe", "크리올어 및 피진어 (영어를 바탕으로 한 기타)", "English-based creoles and pidgins", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "crp", "크리올어 및 피진어 (이외의 언어를 바탕으로 한 기타)", "other creoles and pidgins", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "cpp", "크리올어 및 피진어 (포르투갈어를 바탕으로 한 기타)", "Portuguese-based creoles and pidgins", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "cpf", "크리올어 및 피진어 (프랑스어를 바탕으로 한 기타)", "French-based creoles and pidgins", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("cr", "cre", "크리어", "Cree", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "crh", "크림 타타르어; 크림 튀르크어", "Crimean Turkish; Crimean Tatar", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("km", "khm", "크메르어", "Khmer", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kpe", "크펠레어", "Kpelle", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tlh", "클링온어", "Klingon; tlhIngan-Hol", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ky", "kir", "키르기스어", "Kirghiz", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "gil", "키리바스어", "Gilbertese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ki", "kik", "키쿠유어; 기쿠유어", "Kikuyu; Gikuyu", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("tl", "tgl", "타갈로그어", "Tagalog", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tmh", "타마셰크어", "Tamashek", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ta", "tam", "타밀어", "Tamil", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("th", "tha", "타이어", "Thai", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tai", "타이어군 (기타)", "Tai languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("tg", "tgk", "타지크어", "Tajik", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("tt", "tat", "타타르어", "Tatar", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ty", "tah", "타히티어", "Tahitian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("tr", "tur", "터키어; 튀르크어", "Turkish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ter", "테레나어; 테레노어", "Tereno", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tet", "테툼어", "Tetum", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("te", "tel", "텔루구어", "Telugu", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tem", "템네어", "Timne", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tpi", "톡피신어", "Tok Pisin", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tog", "통가어 (니아사)", "Tonga (Nyasa)", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("to", "ton", "통가어 (통가 제도)", "Tonga (Tonga Islands)", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("tk", "tuk", "투르크멘어", "Turkmen", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tvl", "투발루어", "Tuvalu", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tup", "투피어족", "Tupi languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tyv", "투바어", "Tuvinian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tum", "툼부카어", "Tumbuka", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "ota", "튀르크어 (오스만); 오스만 투르크어 (1500년경-1928년)", "Ottoman Turkish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("tw", "twi", "트위어", "Twi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tli", "틀링깃어", "Tlingit", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tig", "티그레어", "Tigre", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ti", "tir", "티그리냐어", "Tigrinya", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("bo", "tib", "티베트어", "Tibetan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("bo", "bod", "티베트어", "Tibetan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "tiv", "티브어", "Tiv", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ps", "pus", "파슈토어", "Pushto", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "paa", "파푸아 제어 (기타)", "Papuan languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "pap", "파피아멘토어", "Papiamento", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "fat", "판티어", "Fanti", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "pau", "팔라우어", "Palauan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "pal", "팔레비어", "Pahlavi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("pi", "pli", "팔리어", "Pali", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "pam", "팜팡가어; 카팜팡가어", "Pampanga", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "pag", "팡가시난어", "Pangasinan", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "fan", "팡어", "Fang", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("pa", "pan", "펀자브어", "Panjabi; Punjabi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "phn", "페니키아어", "Phoenician", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("fo", "fao", "페로어", "Faroese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("fa", "per", "페르시아어; 파르시어", "Persian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("fa", "fas", "페르시아어; 파르시어", "Persian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "peo", "페르시아어 (고대) (BC 600년-BC 400년경)", "Old Persian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("pt", "por", "포르투갈어", "Portuguese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "fon", "폰어", "Fon", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "pon", "폰페이어; 포나페어", "Pohnpeian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("pl", "pol", "폴란드어", "Polish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ff", "ful", "풀라어", "Fulah; Fulani", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "pra", "프라크리트 제어", "Prakrit languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("fr", "fre", "프랑스어", "French", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("fr", "fra", "프랑스어", "French", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "fro", "프랑스어 (고대) (842년-1400년경)", "Old French", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "frm", "프랑스어 (중세) (1400년-1600년경)", "Middle French", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "pro", "프로방스어 (고대) (1500년 이전)", "Old Provençal", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("fy", "fry", "프리지아어", "Frisian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("fj", "fij", "피지어", "Fijian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("fi", "fin", "핀란드어", "Finnish", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "fiu", "핀우고르어파 (기타)", "Finno-Ugrian languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "fil", "필리핀어", "Filipino; Pilipino", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "phi", "필리핀 제어 (기타)", "Philippine languages", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "haw", "하와이어", "Hawaiian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ha", "hau", "하우사어", "Hausa", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "hai", "하이다어", "Haida", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ko", "kor", "한국어", "Korean", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("hu", "hun", "헝가리어", "Hungarian", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("hz", "her", "헤레로어", "Herero", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "kho", "호탄어", "Khotanese", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "hup", "후파어", "Hupa", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("ho", "hmo", "히리 모투어", "Hiri Motu", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "him", "히마찰어", "Himachali", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("he", "heb", "히브리어", "Hebrew", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "hit", "히타이트어", "Hittite", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("hi", "hin", "힌디어", "Hindi", NOW()+0, "" );
INSERT INTO gbd_language_code (alpha2, alpha3, description1, description2, c_date, u_date) VALUES ("", "hil", "힐리가이노어", "Hiligaynon", NOW()+0, "" );
