INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AF", "AFG", "004", "Afghanistan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AX", "ALA", "248", "Åland Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AL", "ALB", "008", "Albania", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("DZ", "DZA", "012", "Algeria", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AS", "ASM", "016", "American Samoa", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AD", "AND", "020", "Andorra", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AO", "AGO", "024", "Angola", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AI", "AIA", "660", "Anguilla", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AQ", "ATA", "010", "Antarctica", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AG", "ATG", "028", "Antigua and Barbuda", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AR", "ARG", "032", "Argentina", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AM", "ARM", "051", "Armenia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AW", "ABW", "533", "Aruba", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AU", "AUS", "036", "Australia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AT", "AUT", "040", "Austria", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AZ", "AZE", "031", "Azerbaijan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BS", "BHS", "044", "Bahamas", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BH", "BHR", "048", "Bahrain", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BD", "BGD", "050", "Bangladesh", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BB", "BRB", "052", "Barbados", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BY", "BLR", "112", "Belarus", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BE", "BEL", "056", "Belgium", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BZ", "BLZ", "084", "Belize", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BJ", "BEN", "204", "Benin", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BM", "BMU", "060", "Bermuda", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BT", "BTN", "064", "Bhutan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BO", "BOL", "068", "Bolivia, Plurinational State of", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BQ", "BES", "535", "Bonaire, Sint Eustatius and Saba", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BA", "BIH", "070", "Bosnia and Herzegovina", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BW", "BWA", "072", "Botswana", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BV", "BVT", "074", "Bouvet Island", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BR", "BRA", "076", "Brazil", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("IO", "IOT", "086", "British Indian Ocean Territory", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BN", "BRN", "096", "Brunei Darussalam", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BG", "BGR", "100", "Bulgaria", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BF", "BFA", "854", "Burkina Faso", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BI", "BDI", "108", "Burundi", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("KH", "KHM", "116", "Cambodia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CM", "CMR", "120", "Cameroon", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CA", "CAN", "124", "Canada", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CV", "CPV", "132", "Cape Verde", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("KY", "CYM", "136", "Cayman Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CF", "CAF", "140", "Central African Republic", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TD", "TCD", "148", "Chad", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CL", "CHL", "152", "Chile", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CN", "CHN", "156", "China", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CX", "CXR", "162", "Christmas Island", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CC", "CCK", "166", "Cocos (Keeling) Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CO", "COL", "170", "Colombia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("KM", "COM", "174", "Comoros", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CG", "COG", "178", "Congo", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CD", "COD", "180", "Congo, the Democratic Republic of the", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CK", "COK", "184", "Cook Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CR", "CRI", "188", "Costa Rica", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CI", "CIV", "384", "Côte d'Ivoire", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("HR", "HRV", "191", "Croatia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CU", "CUB", "192", "Cuba", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CW", "CUW", "531", "Curaçao", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CY", "CYP", "196", "Cyprus", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CZ", "CZE", "203", "Czech Republic", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("DK", "DNK", "208", "Denmark", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("DJ", "DJI", "262", "Djibouti", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("DM", "DMA", "212", "Dominica", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("DO", "DOM", "214", "Dominican Republic", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("EC", "ECU", "218", "Ecuador", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("EG", "EGY", "818", "Egypt", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SV", "SLV", "222", "El Salvador", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GQ", "GNQ", "226", "Equatorial Guinea", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("ER", "ERI", "232", "Eritrea", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("EE", "EST", "233", "Estonia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("ET", "ETH", "231", "Ethiopia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("FK", "FLK", "238", "Falkland Islands (Malvinas)", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("FO", "FRO", "234", "Faroe Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("FJ", "FJI", "242", "Fiji", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("FI", "FIN", "246", "Finland", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("FR", "FRA", "250", "France", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GF", "GUF", "254", "French Guiana", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PF", "PYF", "258", "French Polynesia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TF", "ATF", "260", "French Southern Territories", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GA", "GAB", "266", "Gabon", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GM", "GMB", "270", "Gambia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GE", "GEO", "268", "Georgia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("DE", "DEU", "276", "Germany", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GH", "GHA", "288", "Ghana", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GI", "GIB", "292", "Gibraltar", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GR", "GRC", "300", "Greece", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GL", "GRL", "304", "Greenland", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GD", "GRD", "308", "Grenada", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GP", "GLP", "312", "Guadeloupe", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GU", "GUM", "316", "Guam", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GT", "GTM", "320", "Guatemala", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GG", "GGY", "831", "Guernsey", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GN", "GIN", "324", "Guinea", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GW", "GNB", "624", "Guinea-Bissau", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GY", "GUY", "328", "Guyana", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("HT", "HTI", "332", "Haiti", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("HM", "HMD", "334", "Heard Island and McDonald Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("VA", "VAT", "336", "Holy See (Vatican City State)", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("HN", "HND", "340", "Honduras", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("HK", "HKG", "344", "Hong Kong", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("HU", "HUN", "348", "Hungary", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("IS", "ISL", "352", "Iceland", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("IN", "IND", "356", "India", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("ID", "IDN", "360", "Indonesia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("IR", "IRN", "364", "Iran, Islamic Republic of", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("IQ", "IRQ", "368", "Iraq", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("IE", "IRL", "372", "Ireland", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("IM", "IMN", "833", "Isle of Man", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("IL", "ISR", "376", "Israel", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("IT", "ITA", "380", "Italy", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("JM", "JAM", "388", "Jamaica", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("JP", "JPN", "392", "Japan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("JE", "JEY", "832", "Jersey", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("JO", "JOR", "400", "Jordan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("KZ", "KAZ", "398", "Kazakhstan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("KE", "KEN", "404", "Kenya", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("KI", "KIR", "296", "Kiribati", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("KP", "PRK", "408", "Korea, Democratic People's Republic of", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("KR", "KOR", "410", "Korea, Republic of", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("KW", "KWT", "414", "Kuwait", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("KG", "KGZ", "417", "Kyrgyzstan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("LA", "LAO", "418", "Lao People's Democratic Republic", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("LV", "LVA", "428", "Latvia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("LB", "LBN", "422", "Lebanon", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("LS", "LSO", "426", "Lesotho", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("LR", "LBR", "430", "Liberia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("LY", "LBY", "434", "Libya", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("LI", "LIE", "438", "Liechtenstein", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("LT", "LTU", "440", "Lithuania", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("LU", "LUX", "442", "Luxembourg", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MO", "MAC", "446", "Macao", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MK", "MKD", "807", "Macedonia, The Former Yugoslav Republic of", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MG", "MDG", "450", "Madagascar", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MW", "MWI", "454", "Malawi", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MY", "MYS", "458", "Malaysia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MV", "MDV", "462", "Maldives", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("ML", "MLI", "466", "Mali", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MT", "MLT", "470", "Malta", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MH", "MHL", "584", "Marshall Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MQ", "MTQ", "474", "Martinique", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MR", "MRT", "478", "Mauritania", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MU", "MUS", "480", "Mauritius", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("YT", "MYT", "175", "Mayotte", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MX", "MEX", "484", "Mexico", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("FM", "FSM", "583", "Micronesia, Federated States of", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MD", "MDA", "498", "Moldova, Republic of", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MC", "MCO", "492", "Monaco", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MN", "MNG", "496", "Mongolia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("ME", "MNE", "499", "Montenegro", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MS", "MSR", "500", "Montserrat", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MA", "MAR", "504", "Morocco", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MZ", "MOZ", "508", "Mozambique", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MM", "MMR", "104", "Myanmar", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NA", "NAM", "516", "Namibia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NR", "NRU", "520", "Nauru", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NP", "NPL", "524", "Nepal", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NL", "NLD", "528", "Netherlands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NC", "NCL", "540", "New Caledonia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NZ", "NZL", "554", "New Zealand", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NI", "NIC", "558", "Nicaragua", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NE", "NER", "562", "Niger", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NG", "NGA", "566", "Nigeria", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NU", "NIU", "570", "Niue", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NF", "NFK", "574", "Norfolk Island", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MP", "MNP", "580", "Northern Mariana Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("NO", "NOR", "578", "Norway", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("OM", "OMN", "512", "Oman", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PK", "PAK", "586", "Pakistan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PW", "PLW", "585", "Palau", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PS", "PSE", "275", "Palestine, State of", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PA", "PAN", "591", "Panama", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PG", "PNG", "598", "Papua New Guinea", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PY", "PRY", "600", "Paraguay", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PE", "PER", "604", "Peru", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PH", "PHL", "608", "Philippines", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PN", "PCN", "612", "Pitcairn", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PL", "POL", "616", "Poland", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PT", "PRT", "620", "Portugal", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PR", "PRI", "630", "Puerto Rico", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("QA", "QAT", "634", "Qatar", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("RE", "REU", "638", "Réunion", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("RO", "ROU", "642", "Romania", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("RU", "RUS", "643", "Russian Federation", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("RW", "RWA", "646", "Rwanda", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("BL", "BLM", "652", "Saint Barthélemy", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SH", "SHN", "654", "Saint Helena, Ascension and Tristan da Cunha", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("KN", "KNA", "659", "Saint Kitts and Nevis", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("LC", "LCA", "662", "Saint Lucia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("MF", "MAF", "663", "Saint Martin (French part)", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("PM", "SPM", "666", "Saint Pierre and Miquelon", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("VC", "VCT", "670", "Saint Vincent and the Grenadines", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("WS", "WSM", "882", "Samoa", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SM", "SMR", "674", "San Marino", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("ST", "STP", "678", "Sao Tome and Principe", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SA", "SAU", "682", "Saudi Arabia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SN", "SEN", "686", "Senegal", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("RS", "SRB", "688", "Serbia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SC", "SYC", "690", "Seychelles", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SL", "SLE", "694", "Sierra Leone", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SG", "SGP", "702", "Singapore", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SX", "SXM", "534", "Sint Maarten (Dutch part)", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SK", "SVK", "703", "Slovakia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SI", "SVN", "705", "Slovenia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SB", "SLB", "090", "Solomon Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SO", "SOM", "706", "Somalia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("ZA", "ZAF", "710", "South Africa", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GS", "SGS", "239", "South Georgia and the South Sandwich Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SS", "SSD", "728", "South Sudan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("ES", "ESP", "724", "Spain", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("LK", "LKA", "144", "Sri Lanka", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SD", "SDN", "729", "Sudan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SR", "SUR", "740", "Suriname", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SJ", "SJM", "744", "Svalbard and Jan Mayen", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SZ", "SWZ", "748", "Swaziland", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SE", "SWE", "752", "Sweden", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("CH", "CHE", "756", "Switzerland", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("SY", "SYR", "760", "Syrian Arab Republic", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TW", "TWN", "158", "Taiwan, Province of China", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TJ", "TJK", "762", "Tajikistan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TZ", "TZA", "834", "Tanzania, United Republic of", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TH", "THA", "764", "Thailand", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TL", "TLS", "626", "Timor-Leste", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TG", "TGO", "768", "Togo", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TK", "TKL", "772", "Tokelau", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TO", "TON", "776", "Tonga", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TT", "TTO", "780", "Trinidad and Tobago", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TN", "TUN", "788", "Tunisia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TR", "TUR", "792", "Turkey", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TM", "TKM", "795", "Turkmenistan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TC", "TCA", "796", "Turks and Caicos Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("TV", "TUV", "798", "Tuvalu", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("UG", "UGA", "800", "Uganda", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("UA", "UKR", "804", "Ukraine", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("AE", "ARE", "784", "United Arab Emirates", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("GB", "GBR", "826", "United Kingdom", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("US", "USA", "840", "United States", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("UM", "UMI", "581", "United States Minor Outlying Islands", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("UY", "URY", "858", "Uruguay", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("UZ", "UZB", "860", "Uzbekistan", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("VU", "VUT", "548", "Vanuatu", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("VE", "VEN", "862", "Venezuela, Bolivarian Republic of", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("VN", "VNM", "704", "Viet Nam", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("VG", "VGB", "092", "Virgin Islands, British", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("VI", "VIR", "850", "Virgin Islands, U.S.", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("WF", "WLF", "876", "Wallis and Futuna", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("EH", "ESH", "732", "Western Sahara", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("YE", "YEM", "887", "Yemen", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("ZM", "ZMB", "894", "Zambia", "", "", NOW()+0, "" );
INSERT INTO gbd_nations (alpha2, alpha3, numberic, name, name_alias, country_call_code, c_date, u_date) VALUES ("ZW", "ZWE", "716", "Zimbabwe", "", "", NOW()+0, "" );
